site_name: MedAISure
site_description: Medical AI Evaluation Benchmark
repo_url: https://github.com/junaidi-ai/MedAISure
repo_name: junaidi-ai/MedAISure
site_dir: site
site_url: https://junaidi-ai.github.io/MedAISure/
use_directory_urls: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Architecture: architecture.md
  - Usage: usage.md
  - Quick Start: quick_start.md
  - Tutorials: tutorials.md
  - Configuration: configuration.md
  - Data Models: data_models.md
  - Metrics:
      - Overview: metrics/overview.md
      - Metric Categories: metrics/metric_categories.md
      - Guidelines: metrics_guidelines.md
      - Testing: metrics_testing.md
      - Clinical Accuracy: metrics/clinical_accuracy.md
      - Reasoning Quality: metrics/reasoning_quality.md
  - Models:
      - Model Interface: models/model_interface.md
      - Local Models: models/local_models.md
      - API Models: models/api_models.md
  - Tasks:
      - Overview: tasks/overview.md
      - Medical QA: tasks/medical_qa.md
      - Diagnostic Reasoning: tasks/diagnostic_reasoning.md
      - Clinical Summarization: tasks/clinical_summarization.md
      - Patient Communication: tasks/patient_communication.md
  - Datasets:
      - Overview: datasets/overview.md
  - API Reference:
      - Overview: api/overview.md
      - Python API: api/reference.md
      - Core API: api/core_api.md
      - CLI: api/cli.md
      - Submission Schema: submission_schema.md
  - Leaderboard:
      - How to Submit: leaderboard/how_to_submit.md
  - Docker: docker.md
  - FAQ: faq.md
  - Testing:
      - Overview: testing.md
      - Guide: testing_guide.md
      - Integration Coverage: testing_integration_coverage.md
  - Performance: performance.md
  - Performance Tips: 04c_performance_tips.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Release Process: release_process.md
  - Security: security.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - Extensions: extensions.md
  - API Reference (Full): api_reference.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.snippets

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            heading_level: 2
