task_type: "diagnostic_reasoning"
name: "Diagnostic Reasoning - Neurology"
description: "Given neurology-related presentations, predict the most likely diagnosis."
input_schema:
  type: "object"
  properties:
    case:
      type: "string"
      description: "Clinical vignette or presentation."
  required: ["case"]
output_schema:
  type: "object"
  properties:
    diagnosis:
      type: "string"
      description: "Predicted diagnosis label."
    confidence:
      type: "number"
      minimum: 0.0
      maximum: 1.0
  required: ["diagnosis"]
metrics:
  - name: "diagnostic_accuracy"
    description: "Accuracy over diagnosis labels."
  - name: "reasoning_quality"
    description: "Heuristic reasoning quality score."

dataset:
  - id: 1
    case: "Acute unilateral facial weakness sparing the forehead; inability to close right eye; hyperacusis."
    diagnosis: "bell_palsy"
  - id: 2
    case: "Sudden severe headache 'worst of life', neck stiffness, negative CT within 6 hours."
    diagnosis: "subarachnoid_hemorrhage"
  - id: 3
    case: "Intention tremor, scanning speech, nystagmus in a 30-year-old female with relapsing neurological deficits."
    diagnosis: "multiple_sclerosis"
