task_type: "diagnostic_reasoning"
name: "Diagnostic Reasoning - Respiratory"
description: "Given clinical presentations, predict the most likely respiratory diagnosis."
inputs:
  - text: "Adult with fever, productive cough, and focal crackles on exam."
  - text: "Smoker with chronic cough, wheezing, and reduced FEV1."
expected_outputs:
  - label: "pneumonia"
  - label: "copd_exacerbation"
input_schema:
  type: "object"
  properties:
    text:
      type: "string"
      description: "Clinical vignette or presentation."
  required: ["text"]
output_schema:
  type: "object"
  properties:
    label:
      type: "string"
      description: "Predicted diagnosis label."
    confidence:
      type: "number"
      minimum: 0.0
      maximum: 1.0
  required: ["label"]
metrics:
  - name: "diagnostic_accuracy"
    description: "Accuracy over diagnosis labels."

dataset:
  - id: 1
    text: "Adult with fever, productive cough, and focal crackles on exam."
    label: "pneumonia"
  - id: 2
    text: "Smoker with chronic cough, wheezing, and reduced FEV1."
    label: "copd_exacerbation"
  - id: 3
    text: "Young adult with sudden pleuritic chest pain and shortness of breath after long flight."
    label: "pulmonary_embolism"
  - id: 4
    text: "Teenager with episodic wheeze, nocturnal cough, and triggers with exercise."
    label: "asthma"
