task_type: "diagnostic_reasoning"
name: "Diagnostic Reasoning - Respiratory"
description: "Given clinical presentations, predict the most likely respiratory diagnosis."
inputs:
  - case: "Adult with fever, productive cough, and focal crackles on exam."
  - case: "Smoker with chronic cough, wheezing, and reduced FEV1."
expected_outputs:
  - diagnosis: "pneumonia"
  - diagnosis: "copd_exacerbation"
input_schema:
  type: "object"
  properties:
    case:
      type: "string"
      description: "Clinical vignette or presentation."
  required: ["case"]
output_schema:
  type: "object"
  properties:
    diagnosis:
      type: "string"
      description: "Predicted diagnosis label."
    confidence:
      type: "number"
      minimum: 0.0
      maximum: 1.0
  required: ["diagnosis"]
metrics:
  - name: "diagnostic_accuracy"
    description: "Accuracy over diagnosis labels."
  - name: "reasoning_quality"
    description: "Heuristic reasoning quality score."

dataset:
  - id: 1
    case: "Adult with fever, productive cough, and focal crackles on exam."
    diagnosis: "pneumonia"
  - id: 2
    case: "Smoker with chronic cough, wheezing, and reduced FEV1."
    diagnosis: "copd_exacerbation"
  - id: 3
    case: "Young adult with sudden pleuritic chest pain and shortness of breath after long flight."
    diagnosis: "pulmonary_embolism"
  - id: 4
    case: "Teenager with episodic wheeze, nocturnal cough, and triggers with exercise."
    diagnosis: "asthma"
