task_type: "qa"
name: "Medical QA - Symptoms"
description: "Answer simple symptom-related medical questions."
inputs:
  - text: "Q: What is a common symptom of influenza?"
  - text: "Q: Name one typical symptom of dehydration in adults."
expected_outputs:
  - answer: "fever"
  - answer: "dry mouth"
input_schema:
  type: "object"
  properties:
    text:
      type: "string"
      description: "The question (may include brief context)."
  required: ["text"]
output_schema:
  type: "object"
  properties:
    answer:
      type: "string"
      description: "The short answer."
    confidence:
      type: "number"
      minimum: 0.0
      maximum: 1.0
  required: ["answer"]
metrics:
  - name: "clinical_correctness"
    description: "Normalized string match between predicted answer and reference answer."

dataset:
  - id: 1
    text: "Q: What is a common symptom of influenza?"
    answer: "fever"
  - id: 2
    text: "Q: Name one typical symptom of dehydration in adults."
    answer: "dry mouth"
  - id: 3
    text: "Q: What symptom often accompanies seasonal allergic rhinitis?"
    answer: "sneezing"
