name: Docs

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python]
      - name: Build docs (strict)
        run: |
          mkdocs build --strict
      - name: Upload Pages artifact (site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
      - name: Link check (Lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          # Use folded scalar to provide a single-line args string to the action
          args: >
            --verbose --no-progress
            --accept 200,206,429
            --exclude-mail
            --exclude-path "site"
            --retry-wait-time 2 --max-retries 2
            "README.md" "README-DEV.md" "README_id.md" "README_ja.md" "README_zh.md" "docs/**/*.md"
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
