name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to create GitHub Releases
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python]

      - name: Build docs
        run: |
          mkdocs build --strict

      - name: Archive site
        run: |
          zip -r site.zip site

      - name: Generate release notes (fallback)
        id: notes
        run: |
          TAG="${GITHUB_REF##*/}"
          PREV_TAG=$(git describe --tags --abbrev=0 "${TAG}^" 2>/dev/null || echo "")
          if [ -n "$PREV_TAG" ]; then
            echo "changes<<EOF" >> $GITHUB_OUTPUT
            git log --pretty=format:'- %s (%h)' ${PREV_TAG}..${TAG} >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "changes<<EOF" >> $GITHUB_OUTPUT
            git log --pretty=format:'- %s (%h)' -n 100 >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            site.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
